= 子网映射
:allow-uri-read: 




=== 子网映射

在此版本中、您可以使用子网映射在故障转移时以新的方式管理IP地址、从而可以为每个vCenter添加子网。执行此操作时、需要为每个虚拟网络定义IPv4 CIDR、默认网关和DNS。

故障转移后、BlueXP  灾难恢复会通过查看为映射的虚拟网络提供的CIDR来确定每个vNIC的适当IP地址、并使用它来派生新的IP地址。

例如：

* 网络A = 10.1.0/24
* 网络B = 192.168.1.0/24


VM1具有一个连接到网络A的vNIC (10.1.1.50)。网络A会在复制计划设置中映射到网络B。

故障转移时、BlueXP  灾难恢复将替换原始IP地址(10.1.1)的网络部分、并保留原始IP地址(10.1.1.50)的主机地址(.50)。对于VM1、BlueXP  灾难恢复会查看网络B的CIDR设置、并使用该网络B网络192.168.1、同时保留主机部分(.50)为VM1创建新的IP地址。新IP变为192.168.1.50。

总之、主机地址保持不变、而网络地址将替换为站点子网映射中配置的任何内容。这样、您就可以更轻松地在故障转移时管理IP地址重新分配、尤其是在需要管理数百个网络和数千个VM的情况下。

有关在站点中包含子网映射的详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["添加vCenter Server站点"]。



=== 跳过保护

现在、您可以跳过保护、这样、在复制计划故障转移之后、服务就不会自动创建反向保护关系。如果要在BlueXP  灾难恢复中将已还原站点恢复联机之前对其执行其他操作、则此功能非常有用。

在您启动故障转移时、如果原始源站点处于联机状态、则默认情况下、该服务会自动为复制计划中的每个卷创建一个反向保护关系。这意味着、该服务将创建从目标站点返回源站点的SnapMirror关系。在您启动故障恢复时、该服务还会自动反转SnapMirror关系。

启动故障转移时，您现在可以选择*Skip protection (跳过保护)*选项。这样、该服务不会自动反转SnapMirror关系。而是将可写卷保留在复制计划的两端。

初始源站点恢复联机后，您可以从“复制计划操作”菜单中选择*Protect Res才 可建立反向保护。此操作会尝试为计划中的每个卷创建反向复制关系。您可以重复运行此作业、直到保护还原为止。恢复保护后、您可以按常规方式启动故障恢复。

有关跳过保护的详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["将应用程序故障转移到远程站点"]。



=== 复制计划中的SnapMirror计划更新

BlueXP  灾难恢复现在支持使用外部快照管理解决方案、例如本机ONTAP SnapMirror策略计划程序或与ONTAP的第三方集成。如果复制计划中的每个数据存储库(卷)都已具有在其他位置管理的SnapMirror关系、则可以在BlueXP  灾难恢复中使用这些快照作为恢复点。

要进行配置、请在复制计划>资源映射部分中、在配置数据存储库映射时选中*使用平台管理的备份和保留计划*复选框。

如果选择此选项、则BlueXP  灾难恢复不会配置备份计划。但是、您仍需要配置保留计划、因为仍可能会为测试、故障转移和故障恢复操作创建快照。

配置此功能后、该服务不会定期创建任何计划的快照、而是依靠外部实体创建和更新这些快照。

有关在复制计划中使用外部快照解决方案的详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。
