---
sidebar: sidebar 
permalink: get-started/dr-setup.html 
keywords: bluexp, disaster recovery, aws, amazon web services, amazon fsx for netapp ontap 
summary: 要使用BlueXP灾难恢复、请执行几个步骤进行设置。 
---
= 为BlueXP灾难恢复设置基础架构
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
要使用BlueXP灾难恢复、请执行几个步骤在Amazon Web Services (AWS)和BlueXP中进行设置。


TIP: 请查看 link:../get-started/dr-prerequisites.html["前提条件"] 以确保您的环境已准备就绪。



== 准备好进行BlueXP灾难恢复

* 验证您的生产环境。
+
** 确保要保护的VM托管在NFS数据存储库(使用ONTAP NFS卷)或VMFS数据存储库(使用NetApp iSCSI LUN)上。
** 确保您拥有内部ONTAP阵列、vCenter和AWS托管的VMware云实例的凭据和访问密钥。


* 创建或验证灾难恢复站点。
+
** 创建或验证您的Amazon FSx文件系统是否已准备就绪。
** 确保源VM和目标VM已建立对等关系。






== 设置适用于AWS SDDC的VMware Cloud

设置适用于AWS软件定义的数据中心(SDDC)的VMware Cloud。

* 创建Amazon FSx for ONTAP文件系统。配置和配置FSx for ONTAP。适用于NetApp ONTAP 的Amazon FSX是一种完全托管的服务、可提供基于常见NetApp ONTAP 文件系统构建的高度可靠、可扩展、高性能和功能丰富的文件存储。
* 按照此处和此处的步骤 https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.html["链接。"^] https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/task-getting-started-fsx.html["适用于NetApp ONTAP 的Amazon FSX快速入门"] 配置和配置FSx for NetApp ONTAP。
* 将Amazon FSx for NetApp ONTAP添加到工作环境中、并添加FSx for ONTAP的AWS凭据。
* 在AWS中、您需要执行以下步骤：
+
** 在AWS上部署和配置VMware Cloud。
** 使用VMware帐户并配置SDDC。确保SDDC已与FSx for ONTAP建立连接。






=== 部署VMware Cloud

https://www.vmware.com/products/vmc-on-aws.html["基于 AWS 的 VMware Cloud"^] 为AWS生态系统中基于VMware的工作负载提供云原生体验。每个VMware软件定义的数据中心(SDDC)都在Amazon虚拟私有云(VPC)中运行、并提供完整的VMware堆栈(包括vCenter Server)、NSX-T软件定义的网络、vSAN软件定义的存储以及一个或多个ESXi主机、用于为工作负载提供计算和存储资源。

要在AWS上配置VMC环境、请按照此处的步骤进行操作 https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html["链接。"^]。指示灯集群还可用于灾难恢复。



== 设置许可

借助BlueXP灾难恢复、您可以注册90天免费试用。

您可以购买以下产品之一：

* AWS Marketplace的按需购买(PAYGO)订阅
* 自带许可证(自带许可证、BYOL)、这是一个NetApp许可证文件(NLL)。


请参阅 link:../get-started/dr-licensing.html["设置BlueXP灾难恢复许可"]。
