---
sidebar: sidebar 
permalink: release-notes/dr-whats-new.html 
keywords: disaster recovery faq, bluexp, disaster recovery frequently asked questions, vmware, vcenter 
summary: BlueXP灾难恢复是一种基于云的灾难恢复服务、可自动执行灾难恢复工作流。 
---
= 新增功能
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解BlueXP灾难恢复预览版中的新增功能。



== 2023年10月20日

此BlueXP灾难恢复预览版包含以下更新。

现在、借助BlueXP灾难恢复功能、您可以保护基于NFS的内部VMware工作负载、使其免受灾难影响、而灾难又发生在公共云之外的另一个基于NFS的内部VMware环境中。BlueXP灾难恢复可安排灾难恢复计划的完成。


NOTE: 对于此预览版产品、NetApp保留在正式发布之前修改产品详细信息、内容和时间表的权利。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["详细了解BlueXP灾难恢复"]。



== 2023年9月27日

此BlueXP灾难恢复预览版包括以下更新：

* *信息板更新*：现在您可以单击信息板上的选项、以便于快速查看信息。此外、信息板现在还会显示故障转移和迁移的状态。
+
请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/dashboard-view.html["在信息板上查看灾难恢复计划的运行状况"]。

* *复制计划更新*：
+
** *RPO *：现在可以在复制计划的数据存储库部分中输入恢复点目标(RPO)和保留计数。这表示必须存在的数据量、这些数据量不应早于设置的时间。例如、如果您将其设置为5分钟、则在发生灾难时、系统可能会丢失长达5分钟的数据、而不会影响业务关键型需求。
+
请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。

** *网络增强功能*：在复制计划的虚拟机部分中映射源位置和目标位置之间的网络时、BlueXP灾难恢复现在提供两个选项：DHCP或静态IP。以前仅支持DHCP。对于静态IP、您需要配置子网、网关和DNS服务器。此外、您现在还可以输入虚拟机的凭据。
+
请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。

** *编辑计划*：现在可以更新复制计划计划。
+
请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["管理资源"]。

** *SnapMirror自动化*：在此版本中创建复制计划时，可以在以下配置之一中定义源卷和目标卷之间的SnapMirror关系：
+
*** 1比1
*** 在扇出架构中排名第一
*** 多对一作为一致性组
*** 多对多
+
请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。









== 2023年8月1日

BlueXP灾难恢复预览是一种基于云的灾难恢复服务、可自动执行灾难恢复工作流。最初、借助BlueXP灾难恢复预览版、您可以使用Amazon FSx for ONTAP保护在AWS上将NetApp存储迁移到VMware Cloud (VMC)的基于NFS的内部VMware工作负载。


NOTE: 对于此预览版产品、NetApp保留在正式发布之前修改产品详细信息、内容和时间表的权利。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["详细了解BlueXP灾难恢复"]。

此版本包含以下更新：

* *启动顺序的资源组更新*：创建灾难恢复或复制计划时，可以将虚拟机添加到功能正常的资源组中。通过资源组、您可以将一组相关虚拟机置于符合您要求的逻辑组中。例如、组可以包含可在恢复时执行的启动顺序。在此版本中、每个资源组可以包含一个或多个虚拟机。虚拟机将根据您将其纳入计划的顺序启动。请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html#select-applications-to-replicate-and-assign-resource-groups["选择要复制的应用程序并分配资源组"]。
* *复制验证*：在创建灾难恢复或复制计划、在向导中确定重复情况并启动向灾难恢复站点的复制之后、BlueXP灾难恢复每30分钟验证一次复制是否根据计划实际进行。您可以在"作业监控器"页面中监控进度。请参见  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/replicate.html["将应用程序复制到其他站点"]。
* *复制计划显示恢复点目标(RPO)传输计划*：创建灾难恢复或复制计划时、请选择VM。在此版本中、您现在可以查看与数据存储库或虚拟机关联的每个卷的SnapMirror。您还可以查看与SnapMirror计划关联的RPO传输计划。RPO可帮助您确定备份计划是否足以在发生灾难后进行恢复。请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。
* *作业监视器更新*：“作业监视器”页现在包含一个刷新选项，以便您可以获得最新的操作状态。请参见  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["监控灾难恢复作业"]。




== 2023年5月18日

这是BlueXP灾难恢复的初始版本。

BlueXP灾难恢复是一种基于云的灾难恢复服务、可自动执行灾难恢复工作流。最初、借助BlueXP灾难恢复预览版、您可以使用Amazon FSx for ONTAP保护在AWS上将NetApp存储迁移到VMware Cloud (VMC)的基于NFS的内部VMware工作负载。

link:https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["详细了解BlueXP灾难恢复"]。
