---
sidebar: sidebar 
permalink: release-notes/dr-whats-new.html 
keywords: disaster recovery, bluexp, disaster recovery, vmware, vcenter, draas, disaster 
summary: BlueXP灾难恢复是一种基于云的灾难恢复服务、可自动执行灾难恢复工作流。借助适用于VMware的BlueXP灾难恢复、您可以使用NetApp云存储将运行ONTAP存储的内部VMware工作负载复制到公有云中的VMware软件定义的数据中心、作为灾难恢复站点。 
---
= BlueXP  灾难恢复中的新增功能
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解BlueXP灾难恢复的新增功能。



== 2025年7月14日

4.2.5版



=== BlueXP disaster recovery中的用户角色

BlueXP disaster recovery现在采用角色来管理每个用户对特定功能和操作的访问权限。

该服务使用特定于BlueXP disaster recovery的以下角色。

* *灾难恢复管理员*：在BlueXP disaster recovery中执行任何操作。
* *灾难恢复故障转移管理*：在BlueXP disaster recovery中执行故障转移和迁移操作。
* *灾难恢复应用程序管理员*：创建和修改复制计划并启动测试故障转移。
* *灾难恢复查看器*：查看BlueXP disaster recovery中的信息，但不能执行任何操作。


如果您单击BlueXP disaster recovery服务并首次对其进行配置，则必须具有 *SnapCenterAdmin* 权限或具有 *Organization Admin* 角色。

有关详细信息，请参见  https://docs.netapp.com/us-en/bluexp-disaster-recovery/reference/dr-reference-roles.html["BlueXP disaster recovery中的用户角色和权限"]。

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["了解所有服务的 BlueXP 访问角色"^](英文)



=== BlueXP disaster recovery中的其他更新

* 增强网络发现
* 可扩展性改进：
+
** 过滤所需的元数据而不是所有细节
** 发现改进，可以更快地检索和更新虚拟机资源
** 数据检索和数据更新的内存优化和性能优化
** vCenter SDK 客户端创建和池管理改进


* 下次计划或手动发现时的陈旧数据管理：
+
** 当在 vCenter 中删除虚拟机时， BlueXP disaster recovery现在会自动将其从复制计划中删除。
** 当 vCenter 中删除数据存储区或网络时， BlueXP disaster recovery现在会将其从复制计划和资源组中删除。
** 当在 vCenter 中删除集群、主机或数据中心时， BlueXP disaster recovery现在会将其从复制计划和资源组中删除。


* 现在，您可以在浏览器的隐身模式下访问 Swagger 文档。您可以在BlueXP disaster recovery中通过“设置”选项 > “API 文档”访问它，也可以在浏览器的隐身模式下直接通过以下 URL 访问它：  https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["Swagger 文档"^] 。
* 在某些情况下，故障回复操作完成后，iGroup 会被遗留。如果 iGroup 已过期，此更新会将其移除。
* 如果复制计划中使用了 NFS FQDN， BlueXP disaster recovery现在会将其解析为 IP 地址。如果灾难恢复站点无法解析 FQDN，则此更新非常有用。
* UI 对齐改进
* 成功发现后，记录捕获 vCenter 大小详细信息的日志改进




== 2025年6月30日

版本4.2.4P2



=== 发现改进

此更新改进了发现过程，从而减少了发现所需的时间。



== 2025年6月23日

版本4.2.4P1



=== 子网映射改进

本次更新增强了“添加和编辑子网映射”对话框，新增了搜索功能。现在，您可以通过输入搜索词快速查找特定子网，从而更轻松地管理子网映射。



== 2025年6月9日

4.2.4版



=== Windows 本地管理员密码解决方案 (LAPS) 支持

Windows 本地管理员密码解决方案 (Windows LAPS) 是一项 Windows 功能，可自动管理和备份 Active Directory 上本地管理员帐户的密码。

现在，您可以通过提供域控制器详细信息来选择子网映射选项并检查 LAPS 选项。使用此选项，您无需为每个虚拟机提供密码。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。



== 2025年5月13日

4.2.3版



=== 子网映射

在此版本中、您可以使用子网映射在故障转移时以新的方式管理IP地址、从而可以为每个vCenter添加子网。执行此操作时、需要为每个虚拟网络定义IPv4 CIDR、默认网关和DNS。

故障转移后、BlueXP  灾难恢复会通过查看为映射的虚拟网络提供的CIDR来确定每个vNIC的适当IP地址、并使用它来派生新的IP地址。

例如：

* 网络A = 10.1.0/24
* 网络B = 192.168.1.0/24


VM1具有一个连接到网络A的vNIC (10.1.1.50)。网络A会在复制计划设置中映射到网络B。

故障转移时、BlueXP  灾难恢复将替换原始IP地址(10.1.1)的网络部分、并保留原始IP地址(10.1.1.50)的主机地址(.50)。对于VM1、BlueXP  灾难恢复会查看网络B的CIDR设置、并使用该网络B网络192.168.1、同时保留主机部分(.50)为VM1创建新的IP地址。新IP变为192.168.1.50。

总之、主机地址保持不变、而网络地址将替换为站点子网映射中配置的任何内容。这样、您就可以更轻松地在故障转移时管理IP地址重新分配、尤其是在需要管理数百个网络和数千个VM的情况下。

有关在站点中包含子网映射的详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["添加vCenter Server站点"]。



=== 跳过保护

现在、您可以跳过保护、这样、在复制计划故障转移之后、服务就不会自动创建反向保护关系。如果要在BlueXP  灾难恢复中将已还原站点恢复联机之前对其执行其他操作、则此功能非常有用。

在您启动故障转移时、如果原始源站点处于联机状态、则默认情况下、该服务会自动为复制计划中的每个卷创建一个反向保护关系。这意味着、该服务将创建从目标站点返回源站点的SnapMirror关系。在您启动故障恢复时、该服务还会自动反转SnapMirror关系。

启动故障转移时，您现在可以选择*Skip protection (跳过保护)*选项。这样、该服务不会自动反转SnapMirror关系。而是将可写卷保留在复制计划的两端。

初始源站点恢复联机后，您可以从“复制计划操作”菜单中选择*Protect Res才 可建立反向保护。此操作会尝试为计划中的每个卷创建反向复制关系。您可以重复运行此作业、直到保护还原为止。恢复保护后、您可以按常规方式启动故障恢复。

有关跳过保护的详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["将应用程序故障转移到远程站点"]。



=== 复制计划中的SnapMirror计划更新

BlueXP  灾难恢复现在支持使用外部快照管理解决方案、例如本机ONTAP SnapMirror策略计划程序或与ONTAP的第三方集成。如果复制计划中的每个数据存储库(卷)都已具有在其他位置管理的SnapMirror关系、则可以在BlueXP  灾难恢复中使用这些快照作为恢复点。

要进行配置、请在复制计划>资源映射部分中、在配置数据存储库映射时选中*使用平台管理的备份和保留计划*复选框。

如果选择此选项、则BlueXP  灾难恢复不会配置备份计划。但是、您仍需要配置保留计划、因为仍可能会为测试、故障转移和故障恢复操作创建快照。

配置此功能后、该服务不会定期创建任何计划的快照、而是依靠外部实体创建和更新这些快照。

有关在复制计划中使用外部快照解决方案的详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。



== 2025年4月16日

4.2.2版



=== 按计划发现VM

BlueXP  灾难恢复每24小时执行一次发现。在此版本中、您现在可以自定义发现计划以满足您的需求、并在需要时减少对性能的影响。例如、如果VM数量很多、则可以将发现计划设置为每48小时运行一次。如果VM数量较少、则可以将发现计划设置为每12小时运行一次。

如果您不想计划发现、则可以禁用计划的发现选项、并随时手动刷新发现。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["添加vCenter Server站点"]。



=== 资源组数据存储库支持

以前、您只能按VM创建资源组。在此版本中、您可以按数据存储库创建资源组。在创建复制计划并为该计划创建资源组时、将列出数据存储库中的所有VM。如果您有大量VM并希望按数据存储库对其进行分组、则此功能非常有用。

您可以通过以下方式使用数据存储库创建资源组：

* 使用数据存储库添加资源组时、您可以看到数据存储库列表。您可以选择一个或多个数据存储库来创建资源组。
* 在创建复制计划并在此计划中创建资源组时、您可以看到数据存储库中的VM。


有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。



=== 免费试用或许可证到期通知

此版本会通知您免费试用版将在60天后过期、以确保您有时间获取许可证。此版本还会在许可证到期当天发出通知。



=== 服务更新通知

在此版本中、顶部会显示一个横幅、指示服务正在升级、并且此服务处于维护模式。升级服务时会显示此横幅、升级完成后此横幅将消失。虽然升级期间您可以继续在UI中工作、但无法提交新作业。计划作业将在更新完成且服务返回到生产模式后运行。



== 2025年3月10日

4.2.1版



=== 智能代理支持

BlueXP  连接器支持智能代理。智能代理是一种将内部环境连接到BlueXP  服务的轻型、安全且高效的方式。它可以在您的环境和BlueXP  服务之间提供安全连接、而无需VPN或直接Internet访问。这种经过优化的代理实施可卸载本地网络中的API流量。

配置代理后、BlueXP  灾难恢复会尝试直接与VMware或ONTAP进行通信、如果直接通信失败、则会使用配置的代理。

实施BlueXP  灾难恢复代理需要使用HTTPS协议在Connector与任何vCenter Server和ONTAP阵列之间进行端口443通信。在执行任何操作时、连接器中的BlueXP  灾难恢复代理会直接与VMware vSphere、VC或ONTAP进行通信。

有关用于BlueXP  灾难恢复的智能代理的详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-setup.html["为BlueXP灾难恢复设置基础架构"]。

有关在BlueXP  中设置常规代理的详细信息，请参见 https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["配置Connector以使用代理服务器"^]。



=== 随时结束免费试用

您可以在任意时间停止免费试用、也可以等到免费试用过期。

请参阅。 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html#end-the-free-trial["结束免费试用"]



== 2025年2月19日

4.2 版



=== ASA R2支持VMFS存储上的VM和数据存储库

此版本的BlueXP  灾难恢复支持对VMFS存储上的VM和数据存储库使用ASA R2。在ASA R2系统上、ONTAP软件支持基本SAN功能、但会删除SAN环境中不支持的功能。

此版本支持ASA R2的以下功能：

* 为主存储配置一致性组(仅限平面一致性组、表示只有一个级别没有分层结构)
* 备份(一致性组)操作、包括SnapMirror自动化


BlueXP  灾难恢复中对ASA R2的支持使用ONTAP 9.161。

虽然数据存储库可以挂载在ONTAP卷或ASA R2存储单元上、但BlueXP  灾难恢复中的资源组不能同时包含ONTAP和ASA R2中的数据存储库。您可以从资源组中的ONTAP或ASA R2选择数据存储库。



== 2024年10月30日



=== 报告

现在、您可以生成并下载报告、以帮助您分析环境。预先设计的报告汇总故障转移和故障恢复、显示所有站点上的复制详细信息、并显示过去七天的作业详细信息。

请参阅 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/reports.html["创建灾难恢复报告"]。



=== 30天免费试用

现在、您可以注册30天免费试用BlueXP  灾难恢复。以前、免费试用期限为90天。

请参阅 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["设置许可"]。



=== 禁用和启用复制计划

先前版本对故障转移测试计划结构进行了更新、需要更新以支持每日和每周计划。此更新要求您禁用并重新启用所有现有复制计划、以便能够使用新的每日和每周故障转移测试计划。这是一次性要求。

方法如下：

. 从顶部菜单中选择*复制计划*。
. 选择一个计划、然后选择操作图标以显示下拉菜单。
. 选择 * 禁用 * 。
. 几分钟后，选择*Enable*。




=== 文件夹映射

现在、在创建复制计划并映射计算资源时、您可以映射文件夹、以便在为数据中心、集群和主机指定的文件夹中恢复VM。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。



=== 可用于故障转移、故障恢复和测试故障转移的VM详细信息

如果发生故障、并且您正在启动故障转移、执行故障恢复或测试故障转移、现在可以查看VM的详细信息并确定哪些VM未重新启动。

请参阅 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["将应用程序故障转移到远程站点"]。



=== VM启动延迟、按顺序启动

现在、在创建复制计划时、您可以为计划中的每个VM设置启动延迟。这样、您就可以设置VM的启动顺序、以确保优先级为一个的所有VM在后续优先级的VM启动之前都处于运行状态。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。



=== VM操作系统信息

创建复制计划时、您现在可以看到该计划中每个VM的操作系统。这有助于确定如何将虚拟机分组到一个资源组中。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。



=== VM名称别名

现在、在创建复制计划时、您可以向灾难恢复SIT上的虚拟机名称添加前缀和后缀。这样、您就可以为计划中的VM使用一个更具描述性的名称。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。



=== 清理旧快照

您可以删除超出指定保留数量的不再需要的任何快照。降低快照保留数量后、快照可能会逐渐累积、您现在可以将其删除以释放空间。您可以随时按需执行此操作、也可以在删除复制计划时执行此操作。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["管理站点、资源组、复制计划、数据存储库和虚拟机信息"]。



=== 协调快照

现在、您可以协调源和目标之间不同步的快照。如果在BlueXP  灾难恢复之外的目标上删除了快照、则可能会发生这种情况。该服务会每24小时自动删除一次源上的快照。但是、您可以按需执行此操作。通过此功能、您可以确保快照在所有站点之间保持一致。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["管理复制计划"]。



== 2024年9月20日



=== 支持从内部到内部的VMware VMFS数据存储库

此版本支持在VMware vSphere虚拟机文件系统(Virtual Machine File System、VMFS)数据存储库上挂载的VM、以便将iSCSI和FC保护到内部存储。以前、该服务提供了一个_technology preview_、支持iSCSI和FC的VMFS数据存储库。

以下是有关iSCSI和FC协议的一些其他注意事项：

* FC支持的是客户端前端协议、而不是复制协议。
* BlueXP  灾难恢复仅支持每个ONTAP卷具有一个LUN。此卷不应具有多个LUN。
* 对于任何复制计划、目标ONTAP卷应使用与托管受保护VM的源ONTAP卷相同的协议。例如、如果源使用FC协议、则目标也应使用FC。




== 2024 年 8 月 2 日



=== 支持使用FC从内部到内部的VMware VMFS数据存储库

此版本为VMware vSphere虚拟机文件系统(VMFS)数据存储库上挂载的VM提供了一个_technology preview_支持、用于将FC保护到内部存储。以前、该服务提供了一个技术预览版、支持将VMFS数据存储库用于iSCSI。


NOTE: NetApp不会对任何预览的工作负载容量收取任何费用。



=== 作业取消

在此版本中、您现在可以在作业监控器UI中取消作业。

请参阅 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["监控作业"]。



== 2024年7月17日



=== 故障转移测试计划

此版本更新了故障转移测试计划结构、支持每日和每周计划需要使用此结构。此更新要求您禁用并重新启用所有现有复制计划、以便能够使用新的每日和每周故障转移测试计划。这是一次性要求。

方法如下：

. 从顶部菜单中选择*复制计划*。
. 选择一个计划、然后选择操作图标以显示下拉菜单。
. 选择 * 禁用 * 。
. 几分钟后，选择*Enable*。




=== 复制计划更新

此版本包含对复制计划数据的更新、可解决"Snapshot not found (找不到快照)"问题。这要求您将所有复制计划中的保留数量更改为1、然后启动按需快照。此过程将创建一个新备份并删除所有较早的备份。

方法如下：

. 从顶部菜单中选择*复制计划*。
. 选择复制计划，单击*故障转移映射*选项卡，然后单击*编辑*铅笔图标。
. 单击*数据存储库*箭头将其展开。
. 记下复制计划中的保留计数值。完成这些步骤后、您需要恢复此原始值。
. 将此计数减少为1。
. 启动按需快照。为此，请在复制计划页面上，选择该计划，单击操作图标，然后选择*立即创建快照*。
. 成功完成快照作业后、将复制计划中的计数增加回您在第一步中记下的原始值。
. 对所有现有复制计划重复上述步骤。




== 2024年7月5日

此BlueXP灾难恢复版本包括以下更新：



=== 支持AFF A系列

此版本支持NetApp AFF A系列硬件平台。



=== 支持从内部到内部的VMware VMFS数据存储库

此版本为受内部存储保护的VMware vSphere虚拟机文件系统(VMFS)数据存储库上装载的VM提供了_technology preview_支持。在此版本中、支持通过技术预览将内部VMware工作负载灾难恢复到具有VMFS数据存储库的内部VMware环境。


NOTE: NetApp不会对任何预览的工作负载容量收取任何费用。



=== 复制计划更新

您可以通过以下方式更轻松地添加复制计划：在"Applications"页面上按数据存储库筛选VM、并在"Resource Mapping "页面上选择更多目标详细信息。请参阅 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。



=== 编辑复制计划

此版本对故障转移映射页面进行了增强、以使其更加清晰。

请参阅 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["管理计划"]。



=== 编辑VM

在此版本中、编辑计划中的VM的过程包括一些小的UI改进。

请参阅 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["管理VM"]。



=== 故障转移更新

现在、在启动故障转移之前、您可以确定虚拟机的状态以及虚拟机是否已启动。现在、您可以通过故障转移过程立即创建快照或选择快照。

请参阅 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["将应用程序故障转移到远程站点"]。



=== 故障转移测试计划

现在、您可以编辑故障转移测试、并为故障转移测试设置每日、每周和每月计划。

请参阅 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["管理计划"]。



=== 更新前提条件信息

已更新BlueXP  灾难恢复前提条件信息。

请参阅 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-prerequisites.html["BlueXP灾难恢复前提条件"]。



== 2024年5月15日

此BlueXP灾难恢复版本包括以下更新：



=== 将VMware工作负载从内部复制到内部

此功能现已作为全面上市功能发布。以前、它是功能有限的技术预览版。



=== 许可更新

借助BlueXP  灾难恢复、您可以注册90天免费试用、通过Amazon Marketplace购买按需购买(PAYGO)订阅、或者自带许可证(BYOL)、这是您从NetApp销售代表或NetApp支持站点(NSS)获取的NetApp许可证文件(NLL)。

有关为BlueXP灾难恢复设置许可的详细信息、请参阅 link:../get-started/dr-licensing.html["设置许可"]。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["详细了解BlueXP灾难恢复"]。



== 2024年3月5日

这是BlueXP灾难恢复的正式发布版本、其中包括以下更新。



=== 许可更新

借助BlueXP  灾难恢复、您可以注册90天免费试用或自带许可证(自带许可证、BYOL)、这是您从NetApp销售代表处获取的NetApp许可证文件(NLL)您可以使用许可证序列号在BlueXP电子钱包中激活BYOL。BlueXP灾难恢复费用基于数据存储库的已配置容量计算。

有关为BlueXP灾难恢复设置许可的详细信息、请参阅 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["设置许可"]。

有关管理*all* BlueXP服务许可证的详细信息，请参阅 https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["管理所有BlueXP服务的许可证"^]。



=== 编辑计划

在此版本中、您现在可以设置计划来测试合规性和故障转移测试、以确保这些计划在您需要时能够正常工作。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。



== 2024年2月1日

此BlueXP灾难恢复预览版包括以下更新：



=== 网络增强

在此版本中、您现在可以调整VM CPU和RAM值的大小。现在、您还可以为虚拟机选择网络DHCP或静态IP地址。

* DHCP：如果选择此选项、则需要提供VM的凭据。
* 静态IP：您可以从源VM选择相同或不同的信息。如果选择与源相同的、则无需输入凭据。另一方面、如果选择使用与源不同的信息、则可以提供凭据、IP地址、子网掩码、DNS和网关信息。


有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。



=== 自定义脚本

现在、可作为故障转移后过程包含在内。通过自定义脚本、您可以在故障转移过程之后让BlueXP灾难恢复运行脚本。例如、您可以使用自定义脚本在故障转移完成后恢复所有数据库事务。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["故障转移到远程站点"]。



=== SnapMirror 关系

现在、您可以在制定复制计划时创建SnapMirror关系。以前、您必须在BlueXP灾难恢复之外创建此关系。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。



=== 一致性组

创建复制计划时、可以包括来自不同卷和不同SVM的VM。BlueXP灾难恢复可通过包含所有卷来创建一致性组快照、并更新所有二级位置。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。



=== VM启动延迟选项

创建复制计划时、您可以将VM添加到资源组。使用资源组、您可以在每个VM上设置延迟、以便它们按延迟顺序启动。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。



=== 应用程序一致的 Snapshot 副本

您可以指定创建应用程序一致的Snapshot副本。该服务将使应用程序处于静修状态、然后创建Snapshot以获得一致的应用程序状态。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。



== 2024年1月11日

此BlueXP灾难恢复预览版包括以下更新：



=== 更快地显示信息板

在此版本中、您可以更快速地从信息板访问其他页面上的信息。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["了解BlueXP灾难恢复"]。



== 2023年10月20日

此BlueXP灾难恢复预览版包含以下更新。



=== 保护基于NFS的内部VMware工作负载

现在、借助BlueXP灾难恢复功能、您可以保护基于NFS的内部VMware工作负载、使其免受灾难影响、而灾难又发生在公共云之外的另一个基于NFS的内部VMware环境中。BlueXP灾难恢复可安排灾难恢复计划的完成。


NOTE: 对于此预览版产品、NetApp保留在正式发布之前修改产品详细信息、内容和时间表的权利。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["详细了解BlueXP灾难恢复"]。



== 2023年9月27日

此BlueXP灾难恢复预览版包括以下更新：



=== 信息板更新

现在、您可以单击信息板上的选项、以便于快速查看信息。此外、信息板现在还会显示故障转移和迁移的状态。

请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/dashboard-view.html["在信息板上查看灾难恢复计划的运行状况"]。



=== 复制计划更新

* *RPO *：现在可以在复制计划的数据存储库部分中输入恢复点目标(RPO)和保留计数。这表示必须存在的数据量、这些数据量不应早于设置的时间。例如、如果您将其设置为5分钟、则在发生灾难时、系统可能会丢失长达5分钟的数据、而不会影响业务关键型需求。
+
请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。

* *网络增强功能*：在复制计划的虚拟机部分中映射源位置和目标位置之间的网络时、BlueXP灾难恢复现在提供两个选项：DHCP或静态IP。以前仅支持DHCP。对于静态IP、您需要配置子网、网关和DNS服务器。此外、您现在还可以输入虚拟机的凭据。
+
请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。

* *编辑计划*：现在可以更新复制计划计划。
+
请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["管理资源"]。

* *SnapMirror自动化*：在此版本中创建复制计划时，可以在以下配置之一中定义源卷和目标卷之间的SnapMirror关系：
+
** 1比1
** 在扇出架构中排名第一
** 多对一作为一致性组
** 多对多
+
请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。







== 2023年8月1日



=== BlueXP  灾难恢复预览

BlueXP灾难恢复预览是一种基于云的灾难恢复服务、可自动执行灾难恢复工作流。最初、借助BlueXP灾难恢复预览版、您可以使用Amazon FSx for ONTAP保护在AWS上将NetApp存储迁移到VMware Cloud (VMC)的基于NFS的内部VMware工作负载。


NOTE: 对于此预览版产品、NetApp保留在正式发布之前修改产品详细信息、内容和时间表的权利。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["详细了解BlueXP灾难恢复"]。

此版本包含以下更新：



=== 资源组会根据启动顺序进行更新

创建灾难恢复或复制计划时、您可以将虚拟机添加到功能正常的资源组中。通过资源组、您可以将一组相关虚拟机置于符合您要求的逻辑组中。例如、组可以包含可在恢复时执行的启动顺序。在此版本中、每个资源组可以包含一个或多个虚拟机。虚拟机将根据您将其纳入计划的顺序启动。请参阅 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html#select-applications-to-replicate-and-assign-resource-groups["选择要复制的应用程序并分配资源组"]。



=== 复制验证

创建灾难恢复或复制计划、在向导中确定重复情况并启动向灾难恢复站点的复制之后、BlueXP  灾难恢复每30分钟验证一次复制是否确实按照计划进行。您可以在"作业监控器"页面中监控进度。请参阅  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/replicate.html["将应用程序复制到其他站点"]。



=== 复制计划显示恢复点目标(RPO)传输计划

在创建灾难恢复或复制计划时、您需要选择VM。在此版本中、您现在可以查看与数据存储库或虚拟机关联的每个卷的SnapMirror。您还可以查看与SnapMirror计划关联的RPO传输计划。RPO可帮助您确定备份计划是否足以在发生灾难后进行恢复。请参阅 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。



=== 作业监视器更新

现在、"作业监控"页面包含"刷新"选项、以便您可以获得最新的操作状态。请参阅  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["监控灾难恢复作业"]。



== 2023年5月18日

这是BlueXP灾难恢复的初始版本。



=== 基于云的灾难恢复服务

BlueXP灾难恢复是一种基于云的灾难恢复服务、可自动执行灾难恢复工作流。最初、借助BlueXP灾难恢复预览版、您可以使用Amazon FSx for ONTAP保护在AWS上将NetApp存储迁移到VMware Cloud (VMC)的基于NFS的内部VMware工作负载。

link:https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["详细了解BlueXP灾难恢复"]。
